spring:
  profiles:
    active: "local"
  main:
    banner-mode: "off"
---
spring:
  profiles: remote
database:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/nh-uat-x?useSSL=true
    username: root
    password: 
    minSize: 1
    maxSize: 5
---
spring:
  profiles: local
database:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&useSSL=true
    username: root
    password: qazwsxedc123
    minSize: 1
    maxSize: 5